# fly.toml app configuration file generated for gde-estoque-api on 2024-10-29T13:59:48-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gde-estoque-api'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[services]

  [[services.http_checks]]
    path = "/health"     
    interval = "15s"     
    grace_period = "10s" 
    timeout = "2s"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1