services:

  sql-server:
    image: lucasmanzi/gde-sql-server:lastest
    container_name: gde-sql-server
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  api-identidade:
    image: lucasmanzi/gde-api-identidade:lastest
    container_name: gde-api-identidade
    build:
      context: ../src
      dockerfile: ./services/GDE.Identidade.API/Dockerfile
    ports:
      - 5101:5101
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5101
