# fly.toml app configuration file generated for gde-estoque-api on 2024-11-17T14:35:14-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gde-estoque-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.Estoque'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
