// <auto-generated />
using System;
using GDE.Pedidos.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GDE.Pedidos.API.Migrations
{
    [DbContext(typeof(PedidosContext))]
    partial class PedidosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GDE.Pedidos.API.Models.PedidoCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdFuncionarioResponsavel")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeFornecedor")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Numero"));

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PedidosCompra");
                });

            modelBuilder.Entity("GDE.Pedidos.API.Models.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocalNome")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("PedidoCompraId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PedidoTransferenciaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PedidoVendaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoCompraId");

                    b.HasIndex("PedidoTransferenciaId");

                    b.HasIndex("PedidoVendaId");

                    b.ToTable("PedidoItens");
                });

            modelBuilder.Entity("GDE.Pedidos.API.Models.PedidoTransferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdFuncionarioResponsavel")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdLocalDestino")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeLocalDestino")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Numero"));

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PedidosTransferencia");
                });

            modelBuilder.Entity("GDE.Pedidos.API.Models.PedidoVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdFuncionarioResponsavel")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Numero"));

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PedidosVenda");
                });

            modelBuilder.Entity("GDE.Pedidos.API.Models.PedidoItem", b =>
                {
                    b.HasOne("GDE.Pedidos.API.Models.PedidoCompra", "PedidoCompra")
                        .WithMany("PedidoItens")
                        .HasForeignKey("PedidoCompraId");

                    b.HasOne("GDE.Pedidos.API.Models.PedidoTransferencia", "PedidoTransferencia")
                        .WithMany("PedidoItens")
                        .HasForeignKey("PedidoTransferenciaId");

                    b.HasOne("GDE.Pedidos.API.Models.PedidoVenda", "PedidoVenda")
                        .WithMany("PedidoItens")
                        .HasForeignKey("PedidoVendaId");

                    b.Navigation("PedidoCompra");

                    b.Navigation("PedidoTransferencia");

                    b.Navigation("PedidoVenda");
                });

            modelBuilder.Entity("GDE.Pedidos.API.Models.PedidoCompra", b =>
                {
                    b.Navigation("PedidoItens");
                });

            modelBuilder.Entity("GDE.Pedidos.API.Models.PedidoTransferencia", b =>
                {
                    b.Navigation("PedidoItens");
                });

            modelBuilder.Entity("GDE.Pedidos.API.Models.PedidoVenda", b =>
                {
                    b.Navigation("PedidoItens");
                });
#pragma warning restore 612, 618
        }
    }
}
